micronaut:
  application:
    name: sketchAvatarApi
  test:
    rollback: true

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true

aws:
  s3:
    bucket:
      legacy: sketch-legacy
      modern: sketch-modern
